import { Router } from 'express';
import { env } from '../config/env';
import { healthRouter } from './health.routes';
import { authRouter } from '../modules/auth/auth.routes';
import { usersRouter } from '../modules/users/users.routes';
import { plantsRouter } from '../modules/plants/plants.routes';
import { departmentsRouter } from '../modules/departments/departments.routes';
import { costCentersRouter } from '../modules/costCenters/cost-centers.routes';
import { rolesRouter } from '../modules/roles/roles.routes';
import { permissionsRouter } from '../modules/permissions/permissions.routes';
import { rbacRouter } from '../modules/permissions/rbac.routes';
import { assetsRouter } from '../modules/assets/assets.routes';
import { workordersRouter } from '../modules/workorders/workorders.routes';
import { pmschedulesRouter } from '../modules/pmSchedules/pmschedules.routes';
import { pmTemplatesRouter } from '../modules/pmSchedules/pm-templates.routes';
import { calibrationRouter } from '../modules/calibration/calibration.routes';
import { amcRouter } from '../modules/amc/amc.routes';
import { vendorsRouter } from '../modules/vendors/vendors.routes';
import { inventoryRouter } from '../modules/inventory/inventory.routes';
import { dataLoggingRouter } from '../modules/datalogging/datalogging.routes';
import { gatesRouter } from '../modules/gates/gates.routes';
import { visitorExperienceRouter } from '../modules/gates/visitor-experience.routes';
import { smartVisitorRouter } from '../modules/gates/smart-visitor.routes';
import { notificationsRouter } from '../modules/notifications/notifications.routes';
import { safetyRouter } from '../modules/safety/safety.routes';
import { esgRouter } from '../modules/esg/esg.routes';
import { esgWorkbookRouter } from '../modules/esg/esg-workbook.routes';
import { reportsRouter } from '../modules/reports/reports.routes';
import { maintenanceReportsRouter } from '../modules/reports/maintenance-reports.routes';
import { mastersRouter } from '../modules/masters/masters.routes';
import { modulesRouter } from '../modules/modules/modules.routes';
import { benchmarkingRouter } from '../modules/benchmarking/benchmarking.routes';
import { performanceLogsRouter } from '../modules/benchmarking/performance-logs.routes';
import { reliabilityRouter } from '../modules/reliability/reliability.routes';
import { esgAdvancedRouter } from '../modules/esg/esg-advanced.routes';
import { alertsRouter } from '../modules/alerts/alerts.routes';
import { securityRouter } from '../modules/security/security.routes';
import { featureFlagsRouter } from '../modules/featureFlags/feature-flags.routes';
import { predictiveRouter } from '../modules/predictive/predictive.routes';
import { insightsRouter } from '../modules/insights/insights.routes';
import { executiveRouter } from '../modules/executive/executive.routes';
import { diagnosticsRouter } from '../modules/diagnostics/diagnostics.routes';
import { qrRouter } from '../modules/qr/qr.routes';
import { organizationsRouter } from '../modules/organizations/organizations.routes';
import { brandingRouter } from '../modules/branding/branding.routes';
import { governanceRouter } from '../modules/governance/governance.routes';
import { rootUsersRouter } from '../modules/root/root-users.routes';
import { rootRoleAccessRouter } from '../modules/root/root-role-access.routes';
import { featuresRouter } from '../modules/features/features.routes';
import { maintenanceTeamsRouter } from '../modules/maintenanceTeams/maintenance-teams.routes';
import { masterDataRouter } from '../modules/master-data/master-data.routes';
import { systemRouter } from '../modules/system/system.routes';
import { shiftsRouter } from '../modules/shifts/shifts.routes';
import { workOrderMastersRouter } from '../modules/workOrderMasters/work-order-masters.routes';
import { pushRouter } from '../modules/push/push.routes';
import { mailRouter } from '../modules/mail/mail.routes';
import { webappLogsRouter } from '../modules/webapp-logs/webapp-logs.routes';
import { reportFormatRouter } from '../modules/report-format/report-format.routes';

export const router = Router();

router.use(healthRouter);
router.use(authRouter);
router.use(brandingRouter);
router.use(pushRouter);
router.use(mailRouter);
router.use(webappLogsRouter);
router.use(reportFormatRouter);
router.use(governanceRouter);
router.use(organizationsRouter);
router.use(rootUsersRouter);
router.use(rootRoleAccessRouter);
router.use(featuresRouter);
router.use(maintenanceTeamsRouter);
router.use(workOrderMastersRouter);
router.use(usersRouter);
router.use(plantsRouter);
router.use(departmentsRouter);
router.use(costCentersRouter);
router.use(rolesRouter);
router.use(permissionsRouter);
router.use(rbacRouter);
router.use(assetsRouter);
router.use(workordersRouter);
router.use(pmschedulesRouter);
router.use(pmTemplatesRouter);
router.use(calibrationRouter);
router.use(amcRouter);
router.use(vendorsRouter);
router.use(inventoryRouter);
router.use(dataLoggingRouter);
router.use(qrRouter);
router.use(gatesRouter);
router.use(visitorExperienceRouter);
router.use(smartVisitorRouter);
router.use(notificationsRouter);
router.use(safetyRouter);
router.use(esgRouter);
router.use(esgWorkbookRouter);
router.use(reportsRouter);
router.use('/maintenance-reports', maintenanceReportsRouter);
router.use(mastersRouter);
router.use('/master-data', masterDataRouter);
router.use(shiftsRouter);
router.use(systemRouter);
router.use('/modules', modulesRouter);
router.use(featureFlagsRouter);
router.use(alertsRouter);
router.use(securityRouter);
if (env.FEATURE_BENCHMARKING) {
  router.use(benchmarkingRouter);
  router.use(performanceLogsRouter);
  router.use(insightsRouter);
  router.use(executiveRouter);
  router.use(predictiveRouter);
}
if (env.FEATURE_RELIABILITY_ADVANCED) {
  router.use(reliabilityRouter);
  router.use(diagnosticsRouter);
}
if (env.FEATURE_ESG_ADVANCED) {
  router.use(esgAdvancedRouter);
}
