export const ESG_WORKBOOK_INPUT_METRICS = [
  { code: 'PRODUCTION_IN_HOUSE', label: 'Production (In-house)', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'PRODUCTION_TOTAL', label: 'Production (Total)', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'RUBBER_COMPOUND_TOTAL', label: 'Rubber Compound (Total)', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'RUBBER_COMPOUND_CAPTIVE', label: 'Rubber Compound (Captive)', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'RUBBER_COMPOUND_OTHER_PLANTS', label: 'Rubber Compound (Other Plants)', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'ELECTRICITY_GROSS', label: 'Electricity (Gross)', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'GRID_ELECTRICITY_NET_PURCHASE', label: 'Grid Electricity (Net Purchase)', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'MAXIMUM_DEMAND', label: 'Maximum Demand', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kVA', aggregation: 'LAST', targetAllowed: true },
  { code: 'ONSITE_SOLAR_GENERATION', label: 'On-site Solar Generation', category: 'RENEWABLES', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'RE_ELECTRICITY', label: 'Renewable Electricity (Wheeled Energy)', category: 'RENEWABLES', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'DG_ELECTRICITY', label: 'DG Electricity', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_ELECTRICITY_CONSUMED', label: 'Total Electricity Consumed', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'FO_EQUIVALENT_FUEL', label: 'FO / Equivalent Fuel', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'ELECTRICITY_GJ', label: 'Electricity in GJ', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'GJ', aggregation: 'SUM', targetAllowed: true },
  { code: 'FO_GJ', label: 'FO in GJ', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'GJ', aggregation: 'SUM', targetAllowed: true },
  { code: 'OTHER_FUELS_GJ', label: 'Other Fuels in GJ', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'GJ', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_ELECTRICITY_RUBBER_COMPOUND', label: 'Total Electricity for Rubber Compound', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'ELECTRICITY_RUBBER_COMPOUND_OTHER_PLANTS', label: 'Electricity for Rubber Compound to Other Plants', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_FO_RUBBER_COMPOUND', label: 'Total FO for Rubber Compound', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'litres', aggregation: 'SUM', targetAllowed: true },
  { code: 'FO_RUBBER_COMPOUND_OTHER_PLANTS', label: 'FO for Rubber Compound to Other Plants', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'litres', aggregation: 'SUM', targetAllowed: true },
  { code: 'WIND_TOTAL_GENERATION', label: 'Wind Total Generation', category: 'RENEWABLES', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'SOLAR_TOTAL_GENERATION', label: 'Solar Total Generation', category: 'RENEWABLES', permissionCategory: 'ENERGY', unit: 'kWh', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_EMISSIONS', label: 'Total Emissions', category: 'EMISSIONS', permissionCategory: 'EMISSIONS', unit: 'tCO2', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_TANKERS', label: 'Raw-water from Tankers', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_PIPED', label: 'Raw-water from Piped Supply', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_BOREWELLS', label: 'Raw-water from Bore-wells', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_RAIN_CAPTURED', label: 'Rainwater Captured in Sump/Pond', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'DRINKING_WATER_PURCHASED', label: 'Drinking Water Purchased', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_RAW_WATER_SOURCED', label: 'Total Raw Water Sourced / Used', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_WATER_RUBBER_COMPOUND', label: 'Total Water Use for Rubber Compound', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'WATER_RUBBER_COMPOUND_OTHER_PLANTS', label: 'Water Use for Rubber Compound to Other Plants', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_AFTER_OTHER_PLANTS', label: 'Raw Water After Other Plants Usage', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAW_WATER_DOMESTIC', label: 'Raw-water Use - Domestic', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAINWATER_POTENTIAL', label: 'Rainwater Potential at Site', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'LAST', targetAllowed: true },
  { code: 'RAINWATER_CAPTURE_AND_USE', label: 'Rainwater Capture and Use', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RAINWATER_RECHARGE', label: 'Rainwater Harvested - Recharge', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'WATER_RETURNED_TO_EARTH_PERCENT', label: 'Water Returned to Earth %', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'LAST', targetAllowed: true },
  { code: 'RAW_WATER_MET_THROUGH_RAINWATER_PERCENT', label: '% Raw Water Met Through Rainwater', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'LAST', targetAllowed: true },
  { code: 'ETP_RECOVERY_PERCENT', label: 'ETP Recovery %', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'LAST', targetAllowed: true },
  { code: 'STP_RECOVERY_PERCENT', label: 'STP Recovery %', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'LAST', targetAllowed: true },
  { code: 'ETP_OUTLET_RECYCLED_FOR_PROCESS_PERCENT', label: '% ETP Outlet Recycled for Process', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'LAST', targetAllowed: true },
  { code: 'RECYCLED_WATER_PROCESS', label: 'Recycled Water Use for Process', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RECYCLED_WATER_FLUSHING', label: 'Recycled Water Use for Flushing', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'RECYCLED_WATER_LANDSCAPING', label: 'Recycled Water Use for Landscaping', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_RECYCLED_WATER', label: 'Total Recycled Water Use', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_FRESH_WATER', label: 'Total Fresh-water Use', category: 'WATER', permissionCategory: 'WATER', unit: 'kL', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_RUBBER', label: 'Rubber Waste (incl compound)', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_BELTS_HOSES', label: 'Belts and Hoses - Scrap', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_METAL_SCRAP', label: 'Metal Scrap', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_ALUMINIUM_COPPER', label: 'Aluminium, Copper, Other', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_PLASTIC', label: 'Plastic Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_PAPER', label: 'Paper Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_WOOD', label: 'Wood Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_FABRIC', label: 'Fabric Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_MISC', label: 'Miscellaneous Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'WASTE_SWEEPING_SCRAP', label: 'Sweeping Scrap', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'HAZ_USED_OIL', label: 'Hazardous Waste - Used Oil', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'HAZ_USED_OIL_FILTER', label: 'Hazardous Waste - Used Oil Filter', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'HAZ_COTTON_WASTE', label: 'Hazardous Waste - Cotton Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'TOTAL_WASTE_GENERATION', label: 'Total Waste Generation', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'PROCESS_WASTE', label: 'Process Waste', category: 'WASTE', permissionCategory: 'WASTE', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_TOTAL_RUBBER', label: 'Total Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_SYNTHETIC_BUTYL', label: 'Synthetic Rubber (Butyl)', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_CHLOROPRENE', label: 'Chloroprene / Neoprene Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_RECLAIMED_RUBBER', label: 'Reclaimed Rubber / Crumb Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_NATURAL_RUBBER', label: 'Natural Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_NITRILE_RUBBER', label: 'Nitrile Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_EPDM_RUBBER', label: 'EPDM Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_FKM_RUBBER', label: 'FKM Rubber', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_REGULAR_CARBON_BLACK', label: 'Regular Carbon Black', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_FILLERS_TYPE_1', label: 'Fillers Type 1', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_ZINC_OXIDE', label: 'Zinc or Zinc Oxide', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_POLYESTER_CORDS', label: 'Polyester Cords', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
  { code: 'MATERIAL_POLYESTER_COTTON_FABRIC', label: 'Polyester / Cotton Fabric', category: 'MATERIALS', permissionCategory: 'PRODUCTION', unit: 'tons', aggregation: 'SUM', targetAllowed: true },
] as const;

export const ESG_WORKBOOK_DERIVED_METRICS = [
  { code: 'OTHER_PLANT_COMPOUND_PERCENT', label: 'Other Plant Compound %', category: 'PRODUCTION', permissionCategory: 'PRODUCTION', unit: '%', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'RE_PERCENT', label: 'RE %', category: 'RENEWABLES', permissionCategory: 'ENERGY', unit: '%', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'TOTAL_ENERGY_GJ', label: 'Total Energy (Power + Fuels)', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'GJ', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'SPECIFIC_ENERGY_POWER', label: 'Specific Energy - Power', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kWh/ton', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'SPECIFIC_ENERGY_FO', label: 'Specific Energy - FO', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'kL/ton', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'SPECIFIC_ENERGY_TOTAL', label: 'Specific Energy (Total)', category: 'ENERGY', permissionCategory: 'ENERGY', unit: 'GJ/ton', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'GHG_INTENSITY', label: 'GHG Intensity', category: 'EMISSIONS', permissionCategory: 'EMISSIONS', unit: 'tCO2/ton', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'SPECIFIC_RAW_WATER', label: 'Specific Raw Water Use', category: 'WATER', permissionCategory: 'WATER', unit: 'kL/ton', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'DOMESTIC_WATER_PERCENT', label: 'Domestic % of Total Water', category: 'WATER', permissionCategory: 'WATER', unit: '%', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'OVERALL_WASTE_PERCENT', label: 'Overall Waste as % of Production', category: 'WASTE', permissionCategory: 'WASTE', unit: '%', aggregation: 'DERIVED', targetAllowed: true },
  { code: 'PROCESS_WASTE_PERCENT', label: 'Process Waste % of Production', category: 'WASTE', permissionCategory: 'WASTE', unit: '%', aggregation: 'DERIVED', targetAllowed: true },
] as const;

export const ESG_WORKBOOK_METRICS = [...ESG_WORKBOOK_INPUT_METRICS, ...ESG_WORKBOOK_DERIVED_METRICS] as const;

export type EsgWorkbookMetricCode = (typeof ESG_WORKBOOK_METRICS)[number]['code'];
export type EsgWorkbookMetricCategory = (typeof ESG_WORKBOOK_METRICS)[number]['category'];

export const ESG_WORKBOOK_METRIC_MAP = new Map(
  ESG_WORKBOOK_METRICS.map((metric) => [metric.code, metric]),
);
