export type AppPermissionAction = "READ" | "CREATE" | "UPDATE" | "DELETE" | "EXPORT" | "APPROVE";
export type AppPageSection = "Operations" | "Masters";
export type AppFeatureKey = "SAFETY" | "ESG" | "GATE_ENTRY" | "ADVANCED_ANALYTICS" | "HR";

export interface AppPageDefinition {
  id: string;
  title: string;
  description: string;
  path: string;
  section: AppPageSection;
  moduleId: string;
  permissionModuleKey: string;
  aliases?: string[];
  featureKey?: AppFeatureKey;
}

export const APP_PERMISSION_ACTIONS: readonly AppPermissionAction[] = [
  "READ",
  "CREATE",
  "UPDATE",
  "DELETE",
  "EXPORT",
  "APPROVE",
];

export const NON_ROOT_APP_PAGES: readonly AppPageDefinition[] = [
  {
    id: "dashboard",
    title: "Dashboard",
    description: "Default landing page with operational KPIs and quick actions.",
    path: "/",
    section: "Operations",
    moduleId: "dashboard",
    permissionModuleKey: "DASHBOARD",
  },
  {
    id: "work-orders",
    title: "Work Orders",
    description: "Plan, assign, and track maintenance work orders.",
    path: "/work-orders",
    section: "Operations",
    moduleId: "workorders",
    permissionModuleKey: "WORK_ORDERS",
  },
  {
    id: "assets",
    title: "Assets",
    description: "Manage machines, equipment, and asset hierarchy.",
    path: "/assets",
    section: "Operations",
    moduleId: "assets",
    permissionModuleKey: "ASSETS",
  },
  {
    id: "preventive-maintenance",
    title: "Preventive Maintenance",
    description: "Control PM and PD schedules, due work, and compliance.",
    path: "/preventive-maintenance",
    section: "Operations",
    moduleId: "pmpd",
    permissionModuleKey: "PM",
    aliases: ["PM_SCHEDULES"],
  },
  {
    id: "calibration",
    title: "Calibration",
    description: "Track calibration schedules, certificates, and overdue instruments.",
    path: "/calibration",
    section: "Operations",
    moduleId: "calibration",
    permissionModuleKey: "CALIBRATION",
  },
  {
    id: "amc",
    title: "AMC Operations",
    description: "Track AMC visits, vendor service activity, SLAs, and coverage dashboards.",
    path: "/amc",
    section: "Operations",
    moduleId: "amc",
    permissionModuleKey: "AMC",
  },
  {
    id: "esg",
    title: "ESG",
    description: "Track plant sustainability data, KPIs, analytics, and ESG reports.",
    path: "/esg",
    section: "Operations",
    moduleId: "esg",
    permissionModuleKey: "ESG",
    featureKey: "ESG",
  },
  {
    id: "inventory",
    title: "Spare Maintenance",
    description: "Maintain machine-wise, critical, and plant-level spare stock.",
    path: "/inventory",
    section: "Operations",
    moduleId: "inventory",
    permissionModuleKey: "INVENTORY",
  },
  {
    id: "reports",
    title: "Reports",
    description: "Review exports, summaries, and scheduled reporting outputs.",
    path: "/reports",
    section: "Operations",
    moduleId: "reports",
    permissionModuleKey: "REPORTS",
  },
  {
    id: "security-center",
    title: "Security Center",
    description: "Review security events, audit logs, and compliance control status.",
    path: "/security-center",
    section: "Operations",
    moduleId: "security-center",
    permissionModuleKey: "MASTERS",
    aliases: ["NOTIFICATIONS"],
  },
  {
    id: "security-gate",
    title: "Digital Gate Entry",
    description: "Record digital gate entries, exits, vehicles, and material movement at plant gates.",
    path: "/security-gate",
    section: "Operations",
    moduleId: "security-gate",
    permissionModuleKey: "GATES",
    featureKey: "GATE_ENTRY",
  },
  {
    id: "visitor-experience",
    title: "Visitor Experience",
    description: "Manage visitor requests, approvals, plant map navigation, and visitor insights.",
    path: "/visitor-experience",
    section: "Operations",
    moduleId: "visitor-experience",
    permissionModuleKey: "GATES",
    aliases: ["VISITOR_EXPERIENCE"],
    featureKey: "GATE_ENTRY",
  },
  {
    id: "logs",
    title: "Logs",
    description: "Capture and review operational and maintenance log entries.",
    path: "/logs",
    section: "Operations",
    moduleId: "logs",
    permissionModuleKey: "LOGS",
  },
  {
    id: "masters",
    title: "Masters Hub",
    description: "Entry page for master-data administration and configuration pages.",
    path: "/masters",
    section: "Masters",
    moduleId: "masters",
    permissionModuleKey: "MASTERS",
  },
  {
    id: "masters-plant",
    title: "Plant Master",
    description: "Maintain plant records, ownership, and operational scope.",
    path: "/masters/plant",
    section: "Masters",
    moduleId: "PLANTS",
    permissionModuleKey: "PLANTS",
    aliases: ["masters.plant"],
  },
  {
    id: "masters-departments",
    title: "Department Master",
    description: "Configure departments, business units, and internal structures.",
    path: "/masters/departments",
    section: "Masters",
    moduleId: "masters.departments",
    permissionModuleKey: "DEPARTMENTS",
  },
  {
    id: "masters-modules",
    title: "Modules Master",
    description: "Manage enabled modules and platform configuration options.",
    path: "/masters/modules",
    section: "Masters",
    moduleId: "masters.modules",
    permissionModuleKey: "MODULES",
    aliases: ["MASTERS.MODULES"],
  },
  {
    id: "masters-machines",
    title: "Machine Master",
    description: "Configure machine categories, types, and linked asset defaults.",
    path: "/masters/machines",
    section: "Masters",
    moduleId: "masters.machines",
    permissionModuleKey: "ASSETS",
  },
  {
    id: "masters-cost-centers",
    title: "Cost Center Master",
    description: "Manage financial ownership structures and cost center mappings.",
    path: "/masters/cost-centers",
    section: "Masters",
    moduleId: "masters.cost-centers",
    permissionModuleKey: "DEPARTMENTS",
  },
  {
    id: "masters-vendors",
    title: "Vendor Master",
    description: "Maintain approved vendors, suppliers, and partner records.",
    path: "/masters/vendors",
    section: "Masters",
    moduleId: "masters.vendors",
    permissionModuleKey: "VENDORS",
  },
  {
    id: "masters-users",
    title: "Users Master",
    description: "Create users, assign roles, and maintain user profiles.",
    path: "/masters/users",
    section: "Masters",
    moduleId: "masters.users",
    permissionModuleKey: "USERS",
  },
  {
    id: "masters-pm-config",
    title: "PM/PD Config",
    description: "Set preventive maintenance rules, intervals, and reminders.",
    path: "/masters/pm-config",
    section: "Masters",
    moduleId: "masters.pm-config",
    permissionModuleKey: "PM",
    aliases: ["PM_SCHEDULES"],
  },
  {
    id: "masters-calibration-config",
    title: "Calibration Config",
    description: "Build calibration templates and link them to machine instruments.",
    path: "/masters/calibration-config",
    section: "Masters",
    moduleId: "masters.calibration-config",
    permissionModuleKey: "CALIBRATION",
  },
  {
    id: "masters-amc-config",
    title: "AMC Master",
    description: "Configure AMC contracts, covered machines, SLAs, and vendor portal assignments.",
    path: "/masters/amc-config",
    section: "Masters",
    moduleId: "masters.amc-config",
    permissionModuleKey: "AMC",
  },
  {
    id: "masters-esg-config",
    title: "ESG Master",
    description: "Configure ESG KPIs, targets, emission factors, and authorized users.",
    path: "/masters/esg-config",
    section: "Masters",
    moduleId: "masters.esg-config",
    permissionModuleKey: "ESG",
    featureKey: "ESG",
  },
  {
    id: "masters-gates",
    title: "Gate Master",
    description: "Configure plant gates and allowed entry-type templates in one place.",
    path: "/masters/gates",
    section: "Masters",
    moduleId: "masters.gates",
    permissionModuleKey: "GATES",
    aliases: ["masters.gate-templates"],
    featureKey: "GATE_ENTRY",
  },
  {
    id: "masters-safety-config",
    title: "Safety Config",
    description: "Manage safety metrics, targets, and plant-level safety configuration.",
    path: "/masters/safety-config",
    section: "Masters",
    moduleId: "masters.safety-config",
    permissionModuleKey: "SAFETY",
    featureKey: "SAFETY",
  },
  {
    id: "masters-email-reports",
    title: "Email Reports Master",
    description: "Schedule automated report delivery, recipients, and reporting sections.",
    path: "/masters/email-reports",
    section: "Masters",
    moduleId: "masters.email-reports",
    permissionModuleKey: "REPORTS",
  },
  {
    id: "masters-log-templates",
    title: "Log Templates Master",
    description: "Configure operational log templates, fields, reminders, and assignments.",
    path: "/masters/log-templates",
    section: "Masters",
    moduleId: "masters.log-templates",
    permissionModuleKey: "LOGS",
  },
  {
    id: "masters-machine-instruments",
    title: "Machine Instruments",
    description: "Register instruments under machines for calibration tracking.",
    path: "/masters/machine-instruments",
    section: "Masters",
    moduleId: "masters.machine-instruments",
    permissionModuleKey: "CALIBRATION",
  },
  {
    id: "masters-shifts",
    title: "Shift Master",
    description: "Define plant shift patterns and shift-based operational coverage.",
    path: "/masters/shifts",
    section: "Masters",
    moduleId: "masters.shifts",
    permissionModuleKey: "SHIFTS",
  },
  {
    id: "masters-maintenance-teams",
    title: "Maintenance Teams Master",
    description: "Create maintenance teams, leaders, and member assignments.",
    path: "/masters/maintenance-teams",
    section: "Masters",
    moduleId: "masters.maintenance-teams",
    permissionModuleKey: "MASTERS",
  },
  {
    id: "masters-work-order-team-mapping",
    title: "Work Order Config",
    description: "Manage work order categories, types, failure codes, and department routing.",
    path: "/masters/work-order-config",
    section: "Masters",
    moduleId: "masters.workorder-team-mapping",
    permissionModuleKey: "MASTERS",
  },
] as const;

export const NON_ROOT_PAGE_SECTIONS = Array.from(new Set(NON_ROOT_APP_PAGES.map((page) => page.section)));

export const NON_ROOT_PERMISSION_MODULE_KEYS = Array.from(
  new Set(NON_ROOT_APP_PAGES.flatMap((page) => [page.permissionModuleKey, ...(page.aliases ?? [])])),
);
