export const APP_ROLES = [
  'ROOT_ADMIN',
  'SUPER_ADMIN',
  'PLANT_ADMIN',
  'ESG_ADMIN',
  'HR_ADMIN',
  'MAINTENANCE_MANAGER',
  'PRODUCTION_MANAGER',
  'SCM_MANAGER',
  'HR_MANAGER',
  'CALIBRATION_MANAGER',
  'ACCOUNTS_MANAGER',
  'SAFETY_MANAGER',
  'ESG_MANAGER',
  'MAINTENANCE_USER',
  'PRODUCTION_USER',
  'SCM_USER',
  'HR_USER',
  'CALIBRATION_USER',
  'ACCOUNTS_USER',
  'SAFETY_USER',
  'ESG_USER',
  'VENDOR',
  'SECURITY',
  'VISITOR',
] as const;

export const MODULES = {
  plants: 'plants',
  users: 'users',
  roles: 'roles',
  permissions: 'permissions',
  assets: 'assets',
  workorders: 'workorders',
  pmpd: 'pmpd',
  calibration: 'calibration',
  amc: 'amc',
  vendors: 'masters.vendors',
  inventory: 'inventory',
  logs: 'logs',
  datalogging: 'data-logging',
  gates: 'security-gate',
  notifications: 'notifications',
  safety: 'safety',
  esg: 'esg',
  reports: 'masters.email-reports',
} as const;
