import path from "path";

export const CONFIG = {
  baseUrl: process.env.BASE_URL || "http://localhost:8081",
  apiUrl: process.env.API_URL || "http://localhost:8081/api",

  credentials: {
    admin: {
      email: process.env.TEST_ADMIN_EMAIL || "mduadmin@jkfenner.com",
      password: process.env.TEST_ADMIN_PASSWORD || "Admin@123!@#",
      plantCode: process.env.TEST_ADMIN_PLANT || "JKF MDU",
    },
    superAdmin: {
      email: process.env.TEST_SUPER_ADMIN_EMAIL || "superadmin@jkfenner.com",
      password: process.env.TEST_SUPER_ADMIN_PASSWORD || "Admin@123!@#",
      plantCode: process.env.TEST_SUPER_ADMIN_PLANT || "JKF MDU",
    },
    rootAdmin: {
      email: process.env.TEST_ROOT_ADMIN_EMAIL || "admin@tamoptix.tech",
      password: process.env.TEST_ROOT_ADMIN_PASSWORD || "TamOptiX@09022026",
      plantCode: process.env.TEST_ROOT_ADMIN_PLANT || "",
    },
    security: {
      email: process.env.TEST_SECURITY_EMAIL || "sample.1@example.com",
      password: process.env.TEST_SECURITY_PASSWORD || "Security@123",
      plantCode: process.env.TEST_SECURITY_PLANT || "JKF MDU",
    },
    vendor: {
      email: process.env.TEST_VENDOR_EMAIL || "sample.4@example.com",
      password: process.env.TEST_VENDOR_PASSWORD || "Vendor@12345",
      plantCode: process.env.TEST_VENDOR_PLANT || "JKF MDU",
    },
    visitor: {
      email: process.env.TEST_VISITOR_EMAIL || "sample.2@example.com",
      password: process.env.TEST_VISITOR_PASSWORD || "Visitor@123!",
      plantCode: process.env.TEST_VISITOR_PLANT || "JKF MDU",
    },
    technician: {
      email: process.env.TEST_TECHNICIAN_EMAIL || "senthilkumar@jkfenner.com",
      password: process.env.TEST_TECHNICIAN_PASSWORD || "Technician@123",
      plantCode: process.env.TEST_TECHNICIAN_PLANT || "JKF MDU",
    },
  },

  timeouts: {
    navigation: 30000,
    action: 15000,
    apiResponse: 20000,
    pageLoad: 20000,
    animation: 1000,
    formSubmit: 5000,
    mobile: {
      navigation: 40000,
      action: 20000,
    },
  },

  screenshots: {
    dir: path.resolve(process.cwd(), "e2e-screenshots"),
  },

  viewports: {
    desktop: { width: 1920, height: 1080 },
    laptop: { width: 1366, height: 768 },
    tablet: { width: 1024, height: 768 },
    ipad: { width: 820, height: 1180 },
    pixel: { width: 393, height: 851 },
    samsung: { width: 412, height: 915 },
    iphone14: { width: 390, height: 844 },
    iphoneSE: { width: 375, height: 667 },
  },

  routes: {
    public: {
      login: "/login",
      qrPublic: "/qr/:token",
      assetPublic: "/assets/:machineCode",
    },
    protected: {
      home: "/",
      dashboard: "/",
      workOrders: "/work-orders",
      assets: "/assets",
      amc: "/amc",
      preventiveMaintenance: "/preventive-maintenance",
      calibration: "/calibration",
      esg: "/esg",
      inventory: "/inventory",
      reports: "/reports",
      securityCenter: "/security-center",
      securityGate: "/security-gate",
      visitorExperience: "/visitor-experience",
      logs: "/logs",
      masters: "/masters",
      technician: "/technician",
      liveScan: "/scan/live",
      forbidden: "/403",
    },
    root: {
      dashboard: "/root/dashboard",
      organizations: "/root/organizations",
      plant: "/root/plant",
      users: "/root/users",
      roleAccess: "/root/role-access",
      mailConfig: "/root/mail-config",
      slaConfig: "/root/sla-config",
    },
    masters: {
      plant: "/masters/plant",
      departments: "/masters/departments",
      modules: "/masters/modules",
      machines: "/masters/machines",
      costCenters: "/masters/cost-centers",
      vendors: "/masters/vendors",
      users: "/masters/users",
      pmConfig: "/masters/pm-config",
      calibrationConfig: "/masters/calibration-config",
      amcConfig: "/masters/amc-config",
      esgConfig: "/masters/esg-config",
      gates: "/masters/gates",
      safetyConfig: "/masters/safety-config",
      emailReports: "/masters/email-reports",
      logTemplates: "/masters/log-templates",
      machineInstruments: "/masters/machine-instruments",
      shifts: "/masters/shifts",
      maintenanceTeams: "/masters/maintenance-teams",
      workOrderConfig: "/masters/work-order-config",
    },
  },

  apiEndpoints: {
    auth: {
      login: "/auth/login",
      refresh: "/auth/refresh",
      logout: "/auth/logout",
      me: "/auth/me",
      changePassword: "/auth/change-password",
      mfaSetup: "/auth/mfa/setup",
      mfaEnable: "/auth/mfa/enable",
      mfaDisable: "/auth/mfa/disable",
      profile: "/auth/profile",
    },
    permissions: {
      me: "/permissions/me",
      rbacMe: "/rbac/permissions/me",
      rbacVersion: "/rbac/version",
    },
    workOrders: {
      list: "/work-orders",
      summary: "/work-orders/summary",
      create: "/work-orders",
      activity: "/work-orders/:id/activity",
      start: "/work-orders/:id/start",
      accept: "/work-orders/:id/accept",
      approve: "/work-orders/:id/approve",
      reject: "/work-orders/:id/reject",
      cancel: "/work-orders/:id/cancel",
      triage: "/work-orders/:id/triage",
      submitForApproval: "/work-orders/:id/submit-for-approval",
    },
    assets: {
      list: "/assets",
      overview: "/assets/:id/overview",
      qr: "/assets/:id/qr",
      qrRotate: "/assets/:id/qr/rotate",
      workOrders: "/assets/:id/work-orders",
    },
    inventory: {
      list: "/inventory",
    },
    amc: {
      list: "/amc",
      dashboard: "/amc/dashboard",
      visits: "/amc/visits",
      serviceReports: "/amc/service-reports",
    },
    pm: {
      schedules: "/pm-schedules",
      templates: "/pm-templates",
      templateLinks: "/pm-template-links",
    },
    calibration: {
      records: "/calibration",
      instruments: "/calibration/instruments",
      templates: "/calibration/templates",
      schedules: "/calibration/schedules",
      tasks: "/calibration/tasks",
    },
    esg: {
      access: "/esg/access",
      dashboard: "/esg/dashboard",
      data: "/esg/data",
      kpis: "/esg/master/kpis",
      analytics: "/esg/analytics",
      reports: "/esg/reports",
    },
    security: {
      dashboard: "/security/dashboard",
      events: "/security/events",
      auditLogs: "/security/audit-logs",
    },
    gates: {
      entries: "/gate-entries",
      dashboard: "/gate-dashboard/summary",
      passes: "/gate-passes/:token",
    },
    visitor: {
      requests: "/visitor-requests",
      profile: "/visitor/profile",
      pass: "/visitor/pass",
      tracking: "/visitor/tracking",
    },
    notifications: {
      list: "/notifications",
      readAll: "/notifications/read-all",
      stream: "/notifications/stream",
    },
    system: {
      health: "/system/health",
      performance: "/system/performance",
    },
  },

  xssPayloads: [
    "<script>alert('xss')</script>",
    "\"><script>alert('xss')</script>",
    "<img src=x onerror=alert('xss')>",
    "javascript:alert('xss')",
    "<svg onload=alert('xss')>",
    "'-prompt(1)-'",
    "<body onload=alert('xss')>",
    '\'"><img src=x onerror=alert("xss")>',
    "{{constructor.constructor('alert(1)')()}}",
    "1;DROP TABLE users",
  ],

  sqliPayloads: [
    "' OR '1'='1",
    "' OR 1=1--",
    "' UNION SELECT NULL--",
    "admin'--",
    "1' OR '1' = '1",
    "1' ORDER BY 1--",
    "' OR '1'='1' /*",
    "'; DROP TABLE users; --",
    "1' AND 1=1",
    "' UNION SELECT * FROM users--",
  ],

  longText: "A".repeat(5000),
  specialChars: "!@#$%^&*()_+-=[]{}|;':\",./<>?~`",
};
